[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo =  'kana/vim-submode'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'udalov/kotlin-vim'
