[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo =  'kana/vim-submode'
hook_source = '''
" Don't dump the key on exiting submode
let g:submode_keep_leaving_key = 1
'''

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'
