alias vim=nvim
alias v=vim
alias g=git
alias restart='exec $SHELL -l'
alias gs='git status -s'
alias gco='git checkout'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log'
alias glol='git log --oneline'
alias gf='git fetch'
alias gm='git merge'
alias gmnf='git merge --no-ff'
alias gfm='git pull'
alias gp='git push'
alias gb='git branch'
alias git=hub
alias ga='git add'
alias gap='git add -p'
